Sample-Projects/ViewComponentSample/Models/ErrorViewModel.cs
namespace ViewComponentSample.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Sample-Projects/ViewComponentSample/Models/TodoItem.cs
namespace ViewComponentSample.Models
{
    public class TodoItem
    {
        public int Id { get; set; }
        public string? Name { get; set; }
        public int Priority { get; set; }
        public bool IsDone { get; set; }
    }
}

Sample-Projects/ViewComponentSample/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using ViewComponentSample.Models;

namespace ViewComponentSample.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Sample-Projects/ViewComponentSample/Controllers/ToDoController.cs
using Microsoft.AspNetCore.Mvc;
using ViewComponentSample.Models;

namespace ViewComponentSample.Controllers;

[Route("[controller]")]
public class ToDoController : Controller
{
    private readonly ToDoContext _context;
    public ToDoController(ToDoContext context)
    {
        _context = context;
        _context.Database.EnsureCreated();
    }

    public IActionResult Index(int maxPriority = 2, bool isDone = false)
    {
        var model = _context.ToDo?.ToList();
        ViewData["maxPriority"] = maxPriority;
        ViewData["isDone"] = isDone;
        return View(model);
    }
}

Sample-Projects/ViewComponentSample/ViewComponents/PriorityListViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ViewComponentSample.Models;

namespace ViewComponentSample.ViewComponents;

public class PriorityListViewComponent : ViewComponent
{
    private readonly ToDoContext _context;
    public PriorityListViewComponent(ToDoContext context)
    {
        _context = context;
    }

    public async Task<IViewComponentResult> InvokeAsync(int maxPriority, bool isDone)
    {
        var items = await GetItemsAsync(maxPriority, isDone);
        return View(items);
    }

    private async Task<List<TodoItem>?> GetItemsAsync(int maxPriority, bool isDone)
    {
        return await _context.ToDo!.Where(x => x.Priority <= maxPriority && x.IsDone == isDone).ToListAsync(); ;
    }
}

Sample-Projects/ViewComponentSample/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Sample-Projects/ViewComponentSample/Views/Shared/Components/PriorityList/Default.cshtml
@model IEnumerable<ViewComponentSample.Models.TodoItem>

<h3>Priority Items</h3>

<ul>
  @foreach (var todo in Model)
  {
    <li>@todo.Name</li>
  }
</ul>

Sample-Projects/ViewComponentSample/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ViewComponentSample</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ViewComponentSample.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ViewComponentSample</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - ViewComponentSample - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Sample-Projects/ViewComponentSample/Views/Todo/Index.cshtml
@using ViewComponentSample.Models
@using ViewComponentSample.ViewComponents
@addTagHelper *, ViewComponentSample
@model IEnumerable<TodoItem>

<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.IsDone)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Priority)
        </th>
    </tr>

    @foreach(var todoItem in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => todoItem.IsDone)
            </td>
            <td>
                @todoItem.Name
            </td>
            <td>
                @Html.DisplayFor(modelItem => todoItem.Priority)
            </td>
        </tr>
    }
</table>

<div>
    Maximum Priority: @ViewData["maxPriority"] <br />
    Is Complete:  @ViewData["isDone"]
       
    @await Component.InvokeAsync(typeof(PriorityListViewComponent), 
        new {maxPriority = ViewData["maxPriority"], isDone = ViewData["isDone"]}
    )

    <vc:priority-list max-priority="2" is-done="false">
    </vc:priority-list>
</div>